FROM debian:bullseye

RUN apt update && apt upgrade -y
RUN apt install apt-utils -y
RUN apt install nano -y
RUN apt install openssh-server -y
RUN apt install net-tools -y
RUN apt install python3 -y
RUN apt install rsync -y
RUN apt install libpcap-dev -y
RUN apt install libmaxminddb-dev -y
RUN apt install gdb -y
